branches:
  only:
    - master

language: rust
rust:
  - 1.38.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - name: rustfmt
      rust: 1.31.0

      install:
        - rustup component add rustfmt

      script:
        - cargo fmt -- --check

    - name: clippy
      rust: 1.31.0

      install:
        - rustup component add clippy-preview

      script:
        - cargo clippy

    - name: WebAssembly
      rust: 1.31.0

      install:
        - rustup target add wasm32-unknown-unknown

      script:
        - cargo check --target wasm32-unknown-unknown
