language: rust
rust:
  - 1.31.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

jobs:
  include:
    - name: clippy
      rust: 1.31.0

      install:
        - rustup component add clippy-preview

      script:
        - cargo clippy
